# Generated by Django 5.2.6 on 2025-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('vip_customer', 'VIP Customer'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
