# Generated by Django 5.2.5 on 2025-09-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0002_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
