# Generated by Django 5.2.5 on 2025-09-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
