# Generated by Django 5.2.5 on 2025-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0007_userprofile_approved_at_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
