# Generated by Django 5.2.5 on 2025-09-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0008_userprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Is_User_Pending',
            field=models.BooleanField(default=True),
        ),
    ]
