# Generated by Django 5.2.5 on 2025-09-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0009_userprofile_is_user_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Is_User_Pending',
        ),
    ]
