# Generated by Django 5.2.5 on 2025-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0010_remove_userprofile_is_user_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
